<a href="https://www.kaggle.com/code/sreenijadreddy/cognizance-task-1-question-2-numpy-operations?scriptVersionId=128531242" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import numpy as np 
arr = [3,4,-2,5,1,-5,25,-6,9]
arr1= [4,16,64,25]

arr = np.array([3, 4, -2, 5, 1, -5, 25, -6, 9])

arr_reshaped = np.reshape(np.sort(arr1), (2, 2))
print("Array arranged and reshaped:")
print(arr_reshaped)

print("\nUNARY FUNCTIONS:\n")

print("ABSOLUTE VALUE\n")
abs_arr1 = np.abs(arr)
abs_arr2 = np.abs(arr1)
print("Absolute value of each element:")
print(abs_arr1,"\n")
print(abs_arr2,"\n")

print("SQUARE ROOT")
sqrt_arr2= np.sqrt(arr1)
print("\nSquare root of each element:")
print("Square root of negative numbers does not exist\n")
print(sqrt_arr2,"\n")

print("EXPONENTIAL VALUE")
exp_arr1 = np.exp(arr)
exp_arr2 = np.exp(arr1)
print("\nExponential value of each element:")
print(exp_arr1,"\n")
print(exp_arr2,"\n")

print("SQUARE")
square_arr1 = np.square(arr)
square_arr2 = np.square(arr1)
print("\nSquare of each element:")
print(square_arr1,"\n")
print(square_arr2,"\n")

print("SINE VALUE")
sin_arr1 = np.sin(arr)
sin_arr2 = np.sin(arr1)
print("\nSine value of each element:")
print(sin_arr1,"\n")
print(sin_arr2,"\n")

print("COSINE VALUE")
cos_arr1 = np.cos(arr)
cos_arr2 = np.cos(arr1)
print("\nCosine value of each element:")
print(cos_arr1,"\n")
print(cos_arr2,"\n")

print("TANGENT VALUE")
tan_arr1 = np.tan(arr)
tan_arr2 = np.tan(arr1)
print("\nTangent value of each element:")
print(tan_arr1,"\n")
print(tan_arr2,"\n")

weight_players = np.array([75, 68, 82, 87, 69])
height_players = np.array([170, 165, 175, 180, 168])
print("\n\nWeight of players:",weight_players,"\n")
print("Height of players:",height_players,"\n")

print("MEAN OF WEIGHT OF THE PLAYERS\n")
mean_weight = np.mean(weight_players)
print("Mean weight of the players:", mean_weight,"\n")

print("SUM OF THE HEIGHT OF THE PLAYERS\n")
sum_height = np.sum(height_players)
print("Sum of height of the players:", sum_height,"\n")

print("STANDARD DEVIATION OF THE WEIGHT OF THE PLAYERS\n")
std_weight = np.std(weight_players)
print("Standard deviation of weight of the players:", std_weight,"\n")

print("STANDARD DEVIATION OF THE HEIGHT OF THE PLAYERS\n")
std_height = np.std(height_players)
print("Standard deviation of height of the players:", std_height,"\n")




Array arranged and reshaped:
[[ 4 16]
 [25 64]]

UNARY FUNCTIONS:

ABSOLUTE VALUE

Absolute value of each element:
[ 3  4  2  5  1  5 25  6  9] 

[ 4 16 64 25] 

SQUARE ROOT

Square root of each element:
Square root of negative numbers does not exist

[2. 4. 8. 5.] 

EXPONENTIAL VALUE

Exponential value of each element:
[2.00855369e+01 5.45981500e+01 1.35335283e-01 1.48413159e+02
 2.71828183e+00 6.73794700e-03 7.20048993e+10 2.47875218e-03
 8.10308393e+03] 

[5.45981500e+01 8.88611052e+06 6.23514908e+27 7.20048993e+10] 

SQUARE

Square of each element:
[  9  16   4  25   1  25 625  36  81] 

[  16  256 4096  625] 

SINE VALUE

Sine value of each element:
[ 0.14112001 -0.7568025  -0.90929743 -0.95892427  0.84147098  0.95892427
 -0.13235175  0.2794155   0.41211849] 

[-0.7568025  -0.28790332  0.92002604 -0.13235175] 

COSINE VALUE

Cosine value of each element:
[-0.9899925  -0.65364362 -0.41614684  0.28366219  0.54030231  0.28366219
  0.99120281  0.96017029 -0.91113026] 

[-0.65364362 -0