<a href="https://www.kaggle.com/code/sreenijadreddy/cognizance-task-1-question-1-numpy?scriptVersionId=128531728" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import numpy as np

print("QUESTION 1\n")
print("SINGLE DIMENSIONAL ARRAY\n")
array1 = np.array([1, 2, 3, 4, 5])
print("Single-dimensional array:")
print(array1,"\n")


print("MULTI-DIMENSIONAL ARRAY\n")
array2 = np.array([[1, 2, 3], [4, 5, 6]])
print("Multi-dimensional array:")
print(array2,"\n")


print("ARRAY OF SPECIFIC RANGE\n")
array3 = np.arange(0, 72, 2)  
print("Array of numbers in a specified range:")
print(array3,"\n")


print("CONVERTING THE ABOVE ARRAY INTO 3X12 ARRRAY\n")
array3_reshape = array3.reshape(3,12)
print("Reshaped array (3 x 12):")
print(array3_reshape,"\n")


print("INVERSE OF A MATRIX\n")
A = np.array([[1, 2],
              [3, 4]])
              

det_A = np.linalg.det(A)

adj_A = np.linalg.inv(A) * det_A

inv_A = adj_A / det_A

print("Matrix A:")
print(A)

print("\nAdjoint of A:")
print(adj_A)

print("\nDeterminant of A")
print(det_A)

print("\nInverse of A:")
print(inv_A)

inverse_mat = np.linalg.inv(A)
print("\nInverse of the matrix:")
print(inverse_mat,"\n")



print("SLICING\n")
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
rows = [0, 1]  
columns = [1, 2]  

selected_rows_columns = array[rows][:, columns]
print("Selected rows and columns:")
print(selected_rows_columns,"\n")


print("IMPORTING DATA\n")
file_path = '/kaggle/input/task-1-dataset-for-question-1-cognizance/numbers.txt'
data = np.loadtxt(file_path)
print("Data loaded from file:")
print(data)





QUESTION 1

SINGLE DIMENSIONAL ARRAY

Single-dimensional array:
[1 2 3 4 5] 

MULTI-DIMENSIONAL ARRAY

Multi-dimensional array:
[[1 2 3]
 [4 5 6]] 

ARRAY OF SPECIFIC RANGE

Array of numbers in a specified range:
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70] 

CONVERTING THE ABOVE ARRAY INTO 3X12 ARRRAY

Reshaped array (3 x 12):
[[ 0  2  4  6  8 10 12 14 16 18 20 22]
 [24 26 28 30 32 34 36 38 40 42 44 46]
 [48 50 52 54 56 58 60 62 64 66 68 70]] 

INVERSE OF A MATRIX

Matrix A:
[[1 2]
 [3 4]]

Adjoint of A:
[[ 4. -2.]
 [-3.  1.]]

Determinant of A
-2.0000000000000004

Inverse of A:
[[-2.   1. ]
 [ 1.5 -0.5]]

Inverse of the matrix:
[[-2.   1. ]
 [ 1.5 -0.5]] 

SLICING

Selected rows and columns:
[[2 3]
 [5 6]] 

IMPORTING DATA

Data loaded from file:
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
